### ISSUE TITLE
Set up tests on Travis CI

### ISSUE THREAD

**Issue by abishekk92** [abishekk92/goset#1]

**Comment by leonardogcsoares** [comment]
Would like to claim this issue! =D

**Comment by jdibiccari** [comment]
Didn't see your comment here @leonardogcsoares ! Don't want to step on anybody's toes so if you want to get a PR in for this it's fine by me!

**Comment by leonardogcsoares** [comment]
Hey @jdibiccari I would really like to get this one (that's why I had try to claim it quick =P) hahaha

**Comment by abishekk92** [comment]
@leonardogcsoares @jdibiccari Haha. It is good to see people competing to claim this issue. (I honestly didn't expect this much attention.) Anyway, If you guys are interested in contributing there are quite a few open issues in the issue tracker, I would be happy to guide you through them.
